version: '3.8'

services:
  nginx:
    image: ${NGINX_IMAGE}
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
